# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Le < Formula
  desc "See and stop what's listening on localhost, from the terminal"
  homepage "https://localhostexplorer.com"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.22/le_0.1.22_darwin_amd64.tar.gz"
      sha256 "70b624aca602b37d9983ea17c9e3bb03de6c2146288d2f834250ba68128dc0cc"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.22/le_0.1.22_darwin_arm64.tar.gz"
      sha256 "a07375919190c99d6e193efc80561b33ac7d4a0c0ec60c4157a6d9bfcaec06c4"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.22/le_0.1.22_linux_amd64.tar.gz"
      sha256 "c6768801e533237fd4fd91d6fbbbc388753c6279c5464997aff8bb518eb550be"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.22/le_0.1.22_linux_arm64.tar.gz"
      sha256 "54abf075da9f69cb105d1a59db89d24785f133d3c4c3621bbb6eae6517dcc149"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  test do
    system "#{bin}/le", "--version"
  end
end
