# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Le < Formula
  desc "See and stop what's listening on localhost, from the terminal"
  homepage "https://localhostexplorer.com"
  version "0.1.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.21/le_0.1.21_darwin_amd64.tar.gz"
      sha256 "227460c641289be97283b8e0864bf3d5206d7f1b0d8233e14c337198babaa700"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.21/le_0.1.21_darwin_arm64.tar.gz"
      sha256 "54f23345ddd2f92cd969b4a5a72839d010846ebaa5b18663c3d842a1cb5df0a7"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.21/le_0.1.21_linux_amd64.tar.gz"
      sha256 "da73079eb94d67d8e0b2a9cd0f095eccb4ecf61a5948eac928229d15a5e6c2b3"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.21/le_0.1.21_linux_arm64.tar.gz"
      sha256 "130a62d70288a42888c26f4e4d7e690fa44912b605d10003371f421a18461ff2"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  test do
    system "#{bin}/le", "--version"
  end
end
