# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Le < Formula
  desc "See and stop what's listening on localhost, from the terminal"
  homepage "https://localhostexplorer.com"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.20/le_0.1.20_darwin_amd64.tar.gz"
      sha256 "fc42140ea48f390aa8afd4adca18063f63e67ec1c273b39d58fb20fd735ee65d"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.20/le_0.1.20_darwin_arm64.tar.gz"
      sha256 "5a789eaf0705ced21824241d69af025ec21dbd7c5772f9a01dba9a3f5a05c764"

      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.20/le_0.1.20_linux_amd64.tar.gz"
      sha256 "214ea55a6034ecf3825813f0a846de99539a26a0b55b4e07742bef22966e577b"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alikatgh/le-cli/releases/download/v0.1.20/le_0.1.20_linux_arm64.tar.gz"
      sha256 "1340b83d858361c9dc3e49491ecd45ceec2a1c055943a8ace72e7514413e4f31"
      define_method(:install) do
        bin.install "le"
        man1.install Dir["man/*.1"]
        # Cobra ships `le completion <shell>`; generate + install so `le <tab>`
        # works out of the box. Runs the just-installed binary at install time,
        # so nothing extra is bundled in the tarball. Homebrew's helper emits
        # zsh + fish for Cobra tools (zsh is the macOS default shell).
        generate_completions_from_executable(bin/"le", "completion")
      end
    end
  end

  test do
    system "#{bin}/le", "--version"
  end
end
